<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>s</string>
	</array>
	<key>firstLineMatch</key>
	<string>; Mode: MSP430 Assembly</string>
	<key>name</key>
	<string>MSP430 Assembly</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>(?x)
				\b(MOVX?|D?ADDC?X?|SUBC?X?|CMPX?|BI(T|C|S)X?|XORX?|ANDX?|RR(C|A)M?|RRUX|RRAX|SWPBX|PUSHM?|SWPB|CALLA?|RETI|SXTX?|JEQ|JZ|JNE|JNZ|JC|JNC|JN|NGE|JL|JMP|ADC|BR|CLR|CLRC|CLRN|CLRZ|DADC|DEC|DECD|DINT|EINT|INCD?|INV|NOP|POP(M|X|)|RET|RL(A|C)M?|SBC|SET(C|N|Z)|TST|ADCX|BRA|RETA|CLRA|CLRX|DADCX|DECX|DECDA|DECDX|INCDA|INCDX|INVX|RLAX|RLCX|DBCX|TSTA|TSTX|POPX)\b([.](B|W|A))?</string>
			<key>name</key>
			<string>keyword.instruction.msp430x</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.instruction.addressmode.msp430x</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>variable.language.register.msp430x</string>
			<key>match</key>
			<string>R([4-9]|(1[0-5]))</string>
		</dict>
		<dict>
			<key>name</key>
			<string>support.variable.register.msp430x</string>
			<key>match</key>
			<string>SR|SP|PC|CG1|CG2</string>
		</dict>
		<dict>
			<key>name</key>
			<string>variable.other.absolute.msp430x</string>
			<key>match</key>
			<string>&amp;((0x[0-9a-fA-F]+)|([0-9]+))</string>
		</dict>
		<dict>
			<key>name</key>
			<string>constant.numeric.immediate.msp430x</string>
			<key>match</key>
			<string>#[0-9]+(x[0-9A-Fa-f]+)?</string>
		</dict>
		<dict>
			<key>name</key>
			<string>variable.other.indexed.msp430x</string>
			<key>match</key>
			<string>((0x[0-9a-fA-F]+)|([0-9]+))\(R[0-9][0-9]?\)</string>
		</dict>
		<dict>
			<key>name</key>
			<string>entity.name.function.label.msp430x</string>
			<key>match</key>
			<string>\b[A-Za-z_][A-Za-z0-9_]*:</string>
		</dict>
		<dict>
			<key>name</key>
			<string>comment.line.double-slash.param.msp430x</string>
			<key>begin</key>
			<string>;\s*(?:arg): ([A-Za-z_][A-Za-z0-9_]*) @ (R[0-9][0-9]?)</string>
			<key>end</key>
			<string>$\n?</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.other.declaration.parameter.msp430x</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.language.register.msp430x</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>comment.line.double-slash.new.msp430x</string>
			<key>begin</key>
			<string>;\s*(?:new): ([A-Za-z_][A-Za-z0-9_]*) @ (R[0-9][0-9]?)</string>
			<key>end</key>
			<string>$\n?</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.other.declaration.msp430x</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.language.register.msp430x</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>comment.line.double-slash.del.msp430x</string>
			<key>begin</key>
			<string>;\s*(?:del): ([A-Za-z_][A-Za-z0-9_]*) @ (R[0-9][0-9]?)</string>
			<key>end</key>
			<string>$\n?</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.other.undeclaration.msp430x</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.language.register.msp430x</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>begin</key>
			<string>;c</string>
			<key>end</key>
			<string>$\n?</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.c</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>name</key>
			<string>comment.line.double-slash.msp430x</string>
			<key>begin</key>
			<string>;</string>
			<key>end</key>
			<string>$\n?</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.msp430x</string>
	<key>uuid</key>
	<string>6e013ee0-666d-11e2-bcfd-0800200c9a66</string>
</dict>
</plist>
